#include "ti_msp_dl_config.h"
#include "laser_pwm_control.h"

/*
 * IOMUX register indices and function codes for the two bridge pins.
 *
 * SysConfig generates GPIO_BRIDGE_PINS_*_IOMUX for the pin indices (these
 * come from the GPIO module we added).  The peripheral function codes are
 * not generated by SysConfig — they come from the device header
 * (mspm0g350x.h, pulled in via msp.h -> ti_msp_dl_config.h).
 *
 *   PA8  PINCM19  GPIO fn = 0x1  TIMA0_CCP0      fn = 0x5
 *   PA22 PINCM47  GPIO fn = 0x1  TIMA0_CCP0_CMPL fn = 0x7
 */
#define PA8_PINCM    BRIDGE_DUMMY_DUMMY_IOMUX   /* IOMUX_PINCM19 */
#define PA22_PINCM   BRIDGE_LASER_LASER_IOMUX   /* IOMUX_PINCM47 */

#define PA8_GPIO_FUNC    IOMUX_PINCM19_PF_GPIOA_DIO08       /* 0x1 */
#define PA22_GPIO_FUNC   IOMUX_PINCM47_PF_GPIOA_DIO22       /* 0x1 */
#define PA8_PWM_FUNC     IOMUX_PINCM19_PF_TIMA0_CCP0        /* 0x5 */
#define PA22_PWM_FUNC    IOMUX_PINCM47_PF_TIMA0_CCP0_CMPL   /* 0x7 */

/*
 * Switch bridge pins to GPIO and lock them to safe output values.
 *
 * Sequence:
 *   1. Write DOUT before touching IOMUX so the moment the pin switches
 *      to GPIO it immediately drives the correct level.
 *   2. Switch PA8 first: dummy path goes GPIO-HIGH while laser is still
 *      PWM-controlled, ensuring current always has somewhere to flow.
 *   3. Switch PA22: laser path goes GPIO-LOW, laser off.
 */
void laser_pins_to_gpio_safe(void)
{
    DL_GPIO_setPins(GPIOA, BRIDGE_DUMMY_DUMMY_PIN);    /* PA8  = 1 */
    DL_GPIO_clearPins(GPIOA, BRIDGE_LASER_LASER_PIN);  /* PA22 = 0 */

    IOMUX->SECCFG.PINCM[PA8_PINCM]  = IOMUX_PINCM_PC_CONNECTED | PA8_GPIO_FUNC;
    IOMUX->SECCFG.PINCM[PA22_PINCM] = IOMUX_PINCM_PC_CONNECTED | PA22_GPIO_FUNC;
}

/*
 * Switch bridge pins to TIMA0 peripheral function.
 *
 * Sequence:
 *   1. Switch PA22 first: laser pin gets PWM control while dummy is still
 *      GPIO-HIGH, so current path is maintained.
 *   2. Switch PA8: dummy path handed to TIMA0_CCP0.  CCP0 is the complement
 *      of CCP0_CMPL, so exactly one of the two transistors is on at any time.
 */
void laser_pins_to_pwm(void)
{
    IOMUX->SECCFG.PINCM[PA22_PINCM] = IOMUX_PINCM_PC_CONNECTED | PA22_PWM_FUNC;
    IOMUX->SECCFG.PINCM[PA8_PINCM]  = IOMUX_PINCM_PC_CONNECTED | PA8_PWM_FUNC;
}
